defaults: &defaults
  working_directory: ~/mern-starter
  docker:
    - image: node:8.3
    - image: mongo:3.4.7

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: make test results folder
          command: mkdir test_results
      - persist_to_workspace:
          root: /root
          paths:
            - mern-starter
            
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root

      - run:
          command: |
            ls -al
            ls -al /root/mern-starter
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test_results
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test_results





workflows:
  version: 2

  btd:
    jobs:
      - build
      - test:
          requires:
            - build

